import Foundation

// MARK: - BridgeMessage

/// A message from JavaScript to the native bridge.
///
/// `BridgeMessage` represents a request from the web layer to invoke
/// a native module action. Each message contains:
/// - A unique request ID for response correlation
/// - The target module name
/// - The action to perform
/// - An optional payload with action-specific data
///
/// ## JSON Format
///
/// ```json
/// {
///   "id": "550e8400-e29b-41d4-a716-446655440000",
///   "module": "haptics",
///   "action": "impact",
///   "payload": { "style": "medium" }
/// }
/// ```
///
/// ## Example
///
/// ```swift
/// let json = """
/// {
///   "id": "abc-123",
///   "module": "platform",
///   "action": "getInfo"
/// }
/// """
///
/// let message = try JSONDecoder().decode(BridgeMessage.self, from: Data(json.utf8))
/// print(message.module)  // "platform"
/// print(message.action)  // "getInfo"
/// print(message.payload) // nil
/// ```
public struct BridgeMessage: Codable, Sendable, Equatable {
    /// Unique request ID for response correlation.
    ///
    /// This is typically a UUID string generated by the JavaScript layer.
    /// The same ID is included in the corresponding `BridgeResponse`.
    public let id: String

    /// The target module name.
    ///
    /// Examples: `"platform"`, `"haptics"`, `"notifications"`
    public let module: String

    /// The action to perform on the module.
    ///
    /// Examples: `"getInfo"`, `"impact"`, `"subscribe"`
    public let action: String

    /// Optional payload with action-specific data.
    ///
    /// The payload structure depends on the module and action.
    /// For example, the haptics `impact` action expects:
    /// ```json
    /// { "style": "medium" }
    /// ```
    public let payload: AnyCodable?

    /// Creates a new bridge message.
    ///
    /// - Parameters:
    ///   - id: Unique request ID (typically a UUID string).
    ///   - module: Target module name.
    ///   - action: Action to perform.
    ///   - payload: Optional action-specific data.
    public init(
        id: String,
        module: String,
        action: String,
        payload: AnyCodable? = nil
    ) {
        self.id = id
        self.module = module
        self.action = action
        self.payload = payload
    }

    /// Creates a new bridge message with an auto-generated UUID.
    ///
    /// - Parameters:
    ///   - module: Target module name.
    ///   - action: Action to perform.
    ///   - payload: Optional action-specific data.
    public init(
        module: String,
        action: String,
        payload: AnyCodable? = nil
    ) {
        self.id = UUID().uuidString
        self.module = module
        self.action = action
        self.payload = payload
    }

    // MARK: - Codable

    private enum CodingKeys: String, CodingKey {
        case id
        case module
        case action
        case payload
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.module = try container.decode(String.self, forKey: .module)
        self.action = try container.decode(String.self, forKey: .action)
        self.payload = try container.decodeIfPresent(AnyCodable.self, forKey: .payload)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(module, forKey: .module)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(payload, forKey: .payload)
    }
}

// MARK: CustomStringConvertible

extension BridgeMessage: CustomStringConvertible {
    public var description: String {
        var parts = ["BridgeMessage(id: \(id), module: \(module), action: \(action)"]
        if let payload {
            parts.append(", payload: \(payload)")
        }
        parts.append(")")
        return parts.joined()
    }
}
